### ISSUE TITLE
/home TP Delay not working

### ISSUE THREAD

**Issue by ghost** [LapisPlugins/HomeSpawn_LEGACY#6]
Good morning,

We have discovered that the TP Delay parameter is not working. It is set to 10 in config, but players are able to /home immediately with no warmup. The following exception is found during server startup in console. File attached due to length of exception:

running spigot 1.12.2 compiled on 2018-02-22
Please let me know what other info you need from me, thank you.

plugin list in load order:

**Comment by Dart2112** [comment]
That error means that there are homes in the player config files that are set in worlds that no longer exist. that error being found stops the config from being loaded and hence the players don't get stopped from teleporting instantly. You need to go through your player configs and remove any homes that have worlds that don't exist

**Comment by Dart2112** [comment]
Multiverse-Core can also cause problems if it loads before homespawn, make sure you have the latest homespawn version as it will fix that if it is the problem. but most of the time it's caused by a world being deleted while homes are still set in it

**Comment by ghost** [comment]
thank you for the feedback. I will review and prune the player data. There is a world we had removed earlier on, so legacy data would make sense. I'll let you know if it persists once it's cleaned up

**Comment by ghost** [comment]
found and deleted playerdata containing old world name. started server successfully with no exceptions:
`[17:16:41] [Server thread/INFO]: [HomeSpawn] Enabling HomeSpawn v2.2.8
[17:16:41] [Server thread/INFO]: [HomeSpawn] 0 Player Data files updated to the new layout
[17:16:41] [Server thread/INFO]: [HomeSpawn] V.2.2.8 Has Been Enabled!
[17:16:41] [Server thread/INFO]: [HomeSpawn] Commands Registered!`

testing home function again, there is still no delay. I am testing with a player who has the `homespawn.player` permission node. I have attached the config file as text.

Do you have a 2.2.9 snapshot build available to players? If so, I'd be happy to try it over the current release 2.2.8

**Comment by Dart2112** [comment]
can you use the /homespawn player (username) command on them so you can see the permission they have been assigned? if that says homespawn.player then I will see what we can do from there. but there might be a permissions problem on your end.

**Comment by ghost** [comment]
the issue went away on its own this morning. Issue resolved. thanks!
