### ISSUE TITLE
Error when players use second home

### ISSUE THREAD

**Issue by Nightreaper77** [LapisPlugins/HomeSpawn_LEGACY#8]
https://i.imgur.com/TVZefee.png

Doesn't seem to happen to me, but all my players get the same error. It only happens when attempting to teleport to any homes following the first, the first seems to work fine. They can also take the wool out of the GUI, not sure if related.

Update: It's now happening to me as well. It basically, instead of tping, allows the player to take the item out of the gui.

**Comment by Dart2112** [comment]
That seems to be an error where the location is null, the code being used to teleport in that instance is old and I will be replacing it shortly. The bug should be fixed in the next version, hopefully that will be out in the next 24-48 hours

**Comment by Nightreaper77** [comment]
Thank you very much!

**Comment by Dart2112** [comment]
[HomeSpawn.zip](https://github.com/LapisPlugins/HomeSpawn/files/2187291/HomeSpawn.zip)
The attached file is a jar with a new UI, it should work and has worked in my testing. let me know how it goes, if it does work I'll update the plugin.

**Comment by Nightreaper77** [comment]
Yeah this one seems to work fine on my test server. How should I go about updating the plugin? I don't want home data to be erased (it's happened before with other plugins).

nvm I just went for it and it worked fine. Yup 100% working on my side. Thanks for the quick fix!

**Comment by Dart2112** [comment]
Awesome, pushing the update out to the public
